### ISSUE TITLE
I have question, I would like to apply for your model. after getting some degree from head pose estimation, How can I use to make frontal landmarks from tilted landmarks by using the angles?

### ISSUE THREAD

**Issue by john09282922** [aliprf/ASMNet#10]

**Comment by aliprf** [comment]
Hi. thank you for your question. 
If I understand your question correctly, you can use the estimated pose to create a boundary for selecting the frontal landmark points. If you provide more details, I can provide more information.

**Comment by john09282922** [comment]
Hi, thank you. Yes, I need more info. And this model is possible to make tf lite?

나의 iPhone에서 보냄

**Comment by aliprf** [comment]
Yes, I think you can convert it to tf lite.

**Comment by john09282922** [comment]
Hi, It works well for ASM Loss 300W.
I have another question for face land mark output.
How can I set the value to check original image?
Because Value is very small under 1.


Thanks,
Jungmin

2022년 10월 23일 (일) 오전 12:57, Ali Pourramezan Fard ***@***.***>님이
작성:

**Comment by aliprf** [comment]
The output of the model is normalized. You need to convert it back to the size of image

**Comment by john09282922** [comment]
Hi, some of output has minus value.
Is it wrong?

Thanks,
Jungmin

나의 iPhone에서 보냄
