### ISSUE TITLE
Similarity transformation for ASM Loss?

### ISSUE THREAD

**Issue by Mkarami3** [aliprf/ASMNet#5]
Dear Ali,
Thanks for sharing your interesting work here.
I am a little bit confused about the way you compute ASM loss.

For computation of landmarks using ASM in other work (or manuscript like Tim Cootes), we are required to do similarity transformation. 

However, in your ASM loss calculation, such transformation is neglected. Am I missing something here?
Thanks

**Comment by aliprf** [comment]
Hi Mohammad,

We are not using the Active Shape Model for localizing the landmark points, so there is no need for transformation. We only use the idea behind the Active Shape Model to create the smooth version of the landmark points, and train the model using those sets. Please read the ASMNet paper for more details.

Thank you,
Ali
