### ISSUE TITLE
Using landmarks to crop the images

### ISSUE THREAD

**Issue by furmandj** [aliprf/ASMNet#6]
From looking through your code it seems like you have to know the landmarks before you can even crop the images appropriately. For a new image not found in the training set, how are you going about getting the landmarks to use to crop **new** images? Are you using dlib? Or am I totally missing something?

This is the part I am talking about inside image_utility.py:

```
class ImageUtility:

    def crop_and_save(self, _image, _label, file_name, num_of_landmarks, dataset_name):
        try:
            '''crop data: we add a small margin to the images'''

            xy_points, x_points, y_points = self.create_landmarks(landmarks=_label,
                                                                      scale_factor_x=1, scale_factor_y=1)
```

**Comment by aliprf** [comment]
The bounding boxes are provided for the testing set of some datasets, or we use the landmark points provided by the dataset to crop the images. If you want to use the code in a real-world application, you need to use face detection software as well.
