### ISSUE TITLE
Normalized Dataset

### ISSUE THREAD

**Issue by wepromen** [aliprf/ASMNet#8]
Dear Mr Ali,
I am a student, can you please share the normalized dataset with the structure below?
Thank you very much!
![image](https://user-images.githubusercontent.com/45889602/172570215-a78519bc-385d-41ad-8e50-38a8588463bf.png)

**Comment by aliprf** [comment]
Hi and thank you for your interest in the repo.
You need to download the dataset from their original websites (see the paper for more detail).
