### ISSUE TITLE
Details about getting pose data？

### ISSUE THREAD

**Issue by Iron-LYK** [aliprf/ASMNet#9]
Hey! Thanks for your great work!
How to use HopeNet to calculate 300W pose data, can you give some guidance or code? Because the yaw angle of the pose data I calculated with HopeNet is very large.
Looking forward to your reply~

**Comment by aliprf** [comment]
Hi. 
Firstly, as I explained in the paper, I normalize the poses. Then, please refer to the HopeNet paper for the details of the pose estimation and the unit they use (degree or radian).
